sonar.organization=lyndorind
sonar.projectKey=lyndorind_demo-repository
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/__main__.py,**/__init__.py
